### ISSUE TITLE
Config file for Java Maven project

### ISSUE THREAD

**Issue by chandan-satyanarayan** [FoelliX/AQL-System#7]
I created a maven project by including the AQL dependency. My console shows the following error message

```
AQL-System 05/11/2022 - 13:04:16 Warning: Cannot find default configuration (config.xml) and no other configuration specified.
AQL-System 05/11/2022 - 13:04:17 [33mWarning: Configuration file does not exist: C:\Users\chand\eclipse-workspace\aql-getting-started\config.xml[m
AQL-System 05/11/2022 - 13:04:17 [33mWarning: Rules file does not exist: C:\Users\chand\eclipse-workspace\aql-getting-started\rules.xml[m
AQL-System 05/11/2022 - 13:04:17 [33mWarning: None of the given rules-files exist![m
AQL-System 05/11/2022 - 13:05:56 [1;32mStarting: Flows IN App('C:\Users\chand\Documents\DroidBench\apk\Aliasing\Merge1.apk') ?[m
AQL-System 05/11/2022 - 13:05:56 Parsed: Flows IN App('C:\Users\chand\Documents\DroidBench\apk\Aliasing\Merge1.apk') ?
AQL-System 05/11/2022 - 13:05:56 No storage file (C:\Users\chand\eclipse-workspace\aql-getting-started\data\storage\storage.ser) found. Continuing with fresh one.
AQL-System 05/11/2022 - 13:05:56
[31mError: Canceled (after 0.119s): Flows IN App('C:\Users\chand\Documents\DroidBench\apk\Aliasing\Merge1.apk') ?
Reason: No appropriate tool could be found to answer the following question: Flows IN App('C:\Users\chand\Documents\DroidBench\apk\Aliasing\Merge1.apk') ?[m
AQL-System 05/11/2022 - 13:05:56 [31mError: No appropriate tool could be found to answer the following question: Flows IN App('C:\Users\chand\Documents\DroidBench\apk\Aliasing\Merge1.apk')
```

Here is a sample of my code 

```
	public static void main(String[] args) {

		final String filePath ="C:\\Users\\chand\\Documents\\DroidBench\\apk\\Aliasing\\Merge1.apk";
		File apkFile = new File(filePath);
		AQLSystem aqlSystem = new AQLSystem();
		Answer answer = (Answer) aqlSystem.queryAndWait("Flows IN App('" + apkFile.getAbsolutePath() + "') ?").iterator().next();
		System.out.println(answer);
	}
```

Am I missing a config file as mentioned [here](https://github.com/FoelliX/AQL-System/wiki/Runthrough) that needs to be configured for the project?

**Comment by FoelliX** [comment]
Yes, in particular for queries asking for "Flows" you need a config that tells the system which tool to execute in order to answer the query. A general tutorial considering the configuration can be found here: https://github.com/FoelliX/AQL-System/wiki/Configuration
The tutorial you linked uses Amandroid 3.1.2 which is not publicly available anymore - I need to update the tutorial.

You can place the config.xml in your projects directory or specify where to find the configuration like this:
```Java
Options options = new Options().setConfig(new File("/path/to/my/config.xml"));
AQLSystem aqlSystem = new AQLSystem(options);
```

If you want to use FlowDroid, you can download it here: https://github.com/secure-software-engineering/FlowDroid/releases/download/v2.10/soot-infoflow-cmd-jar-with-dependencies.jar

An example config could then look like:
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<config>
        <androidPlatforms>path/to/Android/platforms/</androidPlatforms>
        <maxMemory>16</maxMemory>
        <tools>
                <!-- FD 2.10.0 -->
                <tool name="FlowDroid" version="2.10.0" external="false">
                        <priority>4</priority>
                        <timeout>20m</timeout>
                        <execute>
                                <run>java -Xmx%MEMORY%g -jar soot-infoflow-cmd-jar-with-dependencies.jar -a %APP_APK% -p %ANDROID_PLATFORMS% -s SourcesAndSinks.txt -o results/%APP_APK_FILENAME%_result.xml -ol -d</run>
                                <result>/home/fpauck/tools/FlowDroid/2100/results/%APP_APK_FILENAME%_result.xml</result>
                                <instances>0</instances>
                                <memoryPerInstance>4</memoryPerInstance>
                        </execute>
                        <path>/home/fpauck/tools/FlowDroid/2100</path>
                        <questions>IntraAppFlows</questions>
                </tool>
        </tool>
</config>
```
Please note that:
- `<androidPlatforms>path/to/Android/platforms/</androidPlatforms>` must be adapted and point to your Android platforms directory. If you do not have one you can download the required files via Android Studio or use e.g. https://github.com/FoelliX/FX-APD to download them.
- The path `/home/fpauck/tools/FlowDroid/2100/` must be adapted as well.
- FlowDroid requires a SourceAndSinks.txt file. The default one can be downloaded here: https://github.com/secure-software-engineering/FlowDroid/blob/develop/soot-infoflow-android/SourcesAndSinks.txt

Alternatively, you could use an online configuration as described here: https://github.com/FoelliX/AQL-System/wiki/Video_tutorials
Example:
```Java
AQLSystem aqlSystem = new AQLSystem();
CLIHelper.evaluateConfig("http://vm-fpauck.cs.upb.de/AQL-WebService/config, free");
Answer answer = (Answer) aqlSystem.queryAndWait("Flows IN App('DirectLeak1.apk') ?").iterator().next();
System.out.println(Helper.toString(answer));
System.out.println(AnswerHandler.createXMLString(answer));
```
(But currently the remote system is executing other experiments and might be slow or unreachable sometimes.)

**Comment by chandan-satyanarayan** [comment]
Is FlowDroid the only tool that can currently be configured and used with AQL-System?

**Comment by FoelliX** [comment]
No, there are many more:
Amandroid, DidFail, DroidSafe, FlowDroid (all versions), HornDroid, ... (also see https://github.com/FoelliX/AQL-System/blob/master/src/de/foellix/aql/converter/DefaultConverterRegistry.java)
(You can also add more tools. Probably a converter will be required then: https://github.com/FoelliX/AQL-System/wiki/Add_tools)

If you need Amandroid in particular, you can still get it here: https://github.com/arguslab/Argus-SAF/blob/master/binaries/argus-saf-3.2.1-SNAPSHOT-assembly.jar
(that is version 3.2.1 though, 3.1.2 seems to work best for ordinary Android apps - if you need that version pm me, I just do not want to upload a binary here.)

BTW: If you use the remote/online system you can use most of them. But only a limited number of queries per day with a free account. In case you need another account, just let me know.
